import fs from "node:fs";
import { describe, expect, it } from "vitest";
import { expectedAssets, renderAssets, TARGET } from "./embed-logo";

const GUIDE = `## Assets

| File | viewBox | Bar height |
|---|---|---|
| \`public/brand/mark.svg\` | \`0 0 10 10\` | 2.5 |
`;
const SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><title>t</title><path fill="#2A2420" d="M0 0L1 1"/><path fill="#b81d24" d="M1 1L2 2"/></svg>`;

describe("renderAssets", () => {
  it("copies viewBox, clear space and every d, mapping each hex to its role", async () => {
    const out = await renderAssets([{ name: "mark.svg", svg: SVG }], GUIDE);
    expect(out).toMatch(/^\/\/ generated by scripts\/brand\/embed-logo\.ts/);
    expect(out).toContain('"M0 0L1 1"');
    expect(out).toContain('"M1 1L2 2"');
    expect(out).toMatch(/fill: "band",\s+d: "M0 0L1 1"/);
    expect(out).toMatch(/fill: "primary",\s+d: "M1 1L2 2"/);
    expect(out).toContain("clearSpace: 2.5");
    expect(out).not.toMatch(/#[0-9A-Fa-f]{6}/);
  });

  it("refuses a colour outside the brand set and a file the guide does not list", async () => {
    await expect(
      renderAssets([{ name: "mark.svg", svg: SVG.replace("#2A2420", "#3E3934") }], GUIDE),
    ).rejects.toThrow(/no role/);
    await expect(renderAssets([{ name: "other.svg", svg: SVG }], GUIDE)).rejects.toThrow(
      /no bar height/,
    );
  });
});

describe(TARGET, () => {
  it("matches public/brand and docs/design/logo.md (run scripts/brand/embed-logo.ts)", async () => {
    expect(fs.readFileSync(TARGET, "utf8")).toBe(await expectedAssets());
  });
});
