/**
 * The brand marks as component data (#24): reads the seven vectors of public/brand/ (#12, #13) and the
 * Assets table of docs/design/logo.md (#14) and writes src/components/ui/brand/assets.ts, which Wordmark
 * and Monogram render. Paths are copied byte for byte, never redrawn; each brand hex becomes the
 * theme-invariant role that carries it (docs/design/tokens.css), so the components hold no raw colour.
 *
 *   npx tsx scripts/brand/embed-logo.ts          write src/components/ui/brand/assets.ts
 *   npx tsx scripts/brand/embed-logo.ts --check  exit 1 when the committed file drifted from the sources
 *
 * The generated file is checked by scripts/brand/embed-logo.test.ts; never edit it by hand.
 */
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { format } from "prettier";
import { assetsTable, paths, viewBox } from "../lib/brand-svg";

export const BRAND_DIR = "public/brand";
export const GUIDE = "docs/design/logo.md";
export const TARGET = "src/components/ui/brand/assets.ts";

/** Brand hex (the only three the files use, #11) -> role: agit-red, press-ink, paper. */
export const FILL_ROLE: Record<string, BrandRole> = {
  "#B81D24": "primary",
  "#2A2420": "band",
  "#F1E8D6": "band-fg",
};
export type BrandRole = "primary" | "band" | "band-fg";

export type SourceFile = { name: string; svg: string };

/** The data module for `files` (svg sources) given the logo.md text. Pure; throws on unknown input. */
export async function renderAssets(files: SourceFile[], guide: string): Promise<string> {
  const { rows } = assetsTable(guide);
  const marks: Record<string, unknown> = {};
  for (const { name, svg } of [...files].sort((a, b) => a.name.localeCompare(b.name))) {
    const row = rows.find((r) => path.basename(r.file) === name);
    if (!row || !Number.isFinite(row.barHeight))
      throw new Error(`${name}: no bar height in ${GUIDE}`);
    marks[name.replace(/\.svg$/, "")] = {
      viewBox: viewBox(svg),
      clearSpace: row.barHeight,
      paths: paths(svg).map(({ fill, d }) => {
        const role = FILL_ROLE[fill.toUpperCase()];
        if (!role) throw new Error(`${name}: fill ${fill} has no role`);
        return { fill: role, d };
      }),
    };
  }
  const source = `// generated by scripts/brand/embed-logo.ts from ${BRAND_DIR}/*.svg and ${GUIDE}; do not edit
/** A brand fill, as a theme-invariant role of docs/design/tokens.css. */
export type BrandRole = "primary" | "band" | "band-fg";
export type BrandMark = {
  /** The file's own viewBox: x, y, width, height. */
  readonly viewBox: readonly [number, number, number, number];
  /** One bar height in viewBox units (logo.md Assets table): the clear space on every side. */
  readonly clearSpace: number;
  readonly paths: readonly { readonly fill: BrandRole; readonly d: string }[];
};

export const BRAND_MARKS = ${JSON.stringify(marks)} as const satisfies Record<string, BrandMark>;

export type BrandMarkName = keyof typeof BRAND_MARKS;
`;
  return format(source, {
    parser: "typescript",
    semi: true,
    trailingComma: "all",
    printWidth: 100,
  });
}

export function readSources(root = process.cwd()): { files: SourceFile[]; guide: string } {
  const dir = path.join(root, BRAND_DIR);
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".svg"))
    .map((name) => ({ name, svg: fs.readFileSync(path.join(dir, name), "utf8") }));
  return { files, guide: fs.readFileSync(path.join(root, GUIDE), "utf8") };
}

export async function expectedAssets(root = process.cwd()): Promise<string> {
  const { files, guide } = readSources(root);
  return renderAssets(files, guide);
}

async function main() {
  const root = process.cwd();
  const expected = await expectedAssets(root);
  const file = path.join(root, TARGET);
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== expected) {
      console.error(`embed-logo: ${TARGET} is stale (run scripts/brand/embed-logo.ts)`);
      process.exit(1);
    }
    console.log("embed-logo: up to date");
    return;
  }
  fs.writeFileSync(file, expected);
  console.log(`embed-logo: wrote ${TARGET}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) void main();
