import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { EMBED_DIR, EMBEDS, expectedEmbeds, transformEmbed } from "./embeds";

const SAMPLE = `<!doctype html>
<html lang="en">
<head>
<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.184.0/build/three.module.js",
    "three/addons/controls/OrbitControls.js": "https://unpkg.com/three@0.184.0/examples/jsm/controls/OrbitControls.js",
    "three/addons/exporters/OBJExporter.js": "https://unpkg.com/three@0.184.0/examples/jsm/exporters/OBJExporter.js"
  },
  "integrity": { "https://unpkg.com/three@0.184.0/build/three.module.js": "sha384-x" }
}
</script>
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">
</head>
<body><script type="module">import * as THREE from 'three'</script></body>
</html>
`;

describe("transformEmbed", () => {
  const out = transformEmbed(SAMPLE, "sample.html");

  it("serves three.js from /3d/vendor and drops unused specifiers and integrity hashes", () => {
    expect(out).toContain('"three": "/3d/vendor/three.module.min.js"');
    expect(out).toContain(
      '"three/addons/controls/OrbitControls.js": "/3d/vendor/OrbitControls.js"',
    );
    expect(out).not.toContain("OBJExporter");
    expect(out).not.toContain("integrity");
  });

  it("self-hosts the fonts and marks the file as generated", () => {
    expect(out).toContain('<link rel="stylesheet" href="/3d/fonts/embed-fonts.css">');
    expect(out).not.toMatch(/unpkg|googleapis|gstatic/);
    expect(out.split("\n")[1]).toMatch(
      /^<!-- generated by scripts\/embeds\.ts from .*sample\.html/,
    );
  });

  it("refuses a page that would still reach a third party", () => {
    const leaky = SAMPLE.replace("</body>", '<img src="https://example.com/x.png"></body>');
    expect(() => transformEmbed(leaky, "leaky.html")).toThrow(/third-party URL/);
  });
});

describe("public/3d", () => {
  it.each(EMBEDS.map((e) => e.target))("%s matches its bible reference", (target) => {
    const expected = expectedEmbeds().find((e) => e.target === target)!;
    const served = fs.readFileSync(path.join(EMBED_DIR, target), "utf8");
    expect(served).toBe(expected.html);
  });

  it("ships the embed fonts next to the stylesheet", () => {
    const css = fs.readFileSync(path.join(EMBED_DIR, "fonts/embed-fonts.css"), "utf8");
    for (const url of css.match(/url\(([^)]+)\)/g) ?? []) {
      const file = url.replace(/^url\(["']?|["']?\)$/g, "");
      expect(fs.existsSync(path.join(EMBED_DIR, "fonts", file)), file).toBe(true);
    }
  });
});
