/**
 * The app's 3D embeds (design bible 9, 14.1, 14.3, 15, 16): the bible's reference pages, plus pages
 * built from them under `docs/design/embeds/`, are served as-is from `public/3d/`, in iframes, with two
 * changes so the app depends on no third party at runtime:
 *   - the importmap points at `/3d/vendor/` (three.js r184 copied from node_modules, gitignored)
 *   - the Google Fonts link becomes `/3d/fonts/embed-fonts.css` (the same faces, self-hosted)
 *
 *   npx tsx scripts/embeds.ts          write public/3d/*.html from the bible and copy the vendor files
 *   npx tsx scripts/embeds.ts vendor   copy the vendor files only (postinstall)
 *   npx tsx scripts/embeds.ts --check  exit 1 when a committed public/3d/*.html drifted from its reference
 *
 * `public/3d/*.html` is committed and checked by scripts/embeds.test.ts; never edit it by hand.
 */
import fs from "node:fs";
import path from "node:path";

export const BIBLE_DIR = "docs/design/bible";
export const APP_EMBED_DIR = "docs/design/embeds";
export const EMBED_DIR = "public/3d";
export const VENDOR_DIR = `${EMBED_DIR}/vendor`;
export const FONTS_CSS = "/3d/fonts/embed-fonts.css";

/** Source page -> served embed (bible 16). */
export const EMBEDS = [
  { source: `${BIBLE_DIR}/Fifth Copy Full Lobby.html`, target: "lobby.html" },
  { source: `${BIBLE_DIR}/Fifth Copy Your Clerk.html`, target: "clerk.html" },
  { source: `${BIBLE_DIR}/Fifth Copy Medal.html`, target: "medal.html" },
  { source: `${APP_EMBED_DIR}/Fifth Copy The Major.html`, target: "major.html" },
] as const;

/** three.js r184 files served from `/3d/vendor/` (bible 9: pinned engine). */
export const VENDOR_FILES = [
  "build/three.module.min.js",
  "build/three.core.min.js",
  "examples/jsm/controls/OrbitControls.js",
] as const;

/** Bare specifier -> served path; specifiers absent here are dropped (the pages never import them). */
const IMPORTS: Record<string, string> = {
  three: "/3d/vendor/three.module.min.js",
  "three/addons/controls/OrbitControls.js": "/3d/vendor/OrbitControls.js",
};

const IMPORTMAP_RE = /<script type="importmap">\s*([\s\S]*?)\s*<\/script>/;
const FONT_LINK_RE = /<link[^>]*fonts\.googleapis\.com[^>]*>\n?/g;
const THIRD_PARTY_RE = /https?:\/\/(?!www\.w3\.org\/)[^\s"')]+/;

/** Rewrites one reference page into its served embed. Throws when an external URL would remain. */
export function transformEmbed(html: string, source: string): string {
  const match = IMPORTMAP_RE.exec(html);
  if (!match) throw new Error(`${source}: no importmap`);
  const map = JSON.parse(match[1]!) as { imports: Record<string, string> };
  const imports: Record<string, string> = {};
  for (const specifier of Object.keys(map.imports)) {
    const served = IMPORTS[specifier];
    if (served) imports[specifier] = served;
  }
  const importmap = `<script type="importmap">\n${JSON.stringify({ imports }, null, 2)}\n</script>`;
  const out = html
    .replace(IMPORTMAP_RE, importmap)
    .replace(FONT_LINK_RE, `<link rel="stylesheet" href="${FONTS_CSS}">\n`)
    .replace(
      /^(<!doctype html>\n?)/i,
      `$1<!-- generated by scripts/embeds.ts from ${source}; do not edit -->\n`,
    );
  const external = THIRD_PARTY_RE.exec(out);
  if (external) throw new Error(`${source}: third-party URL left in the embed: ${external[0]}`);
  return out;
}

export function expectedEmbeds(root = process.cwd()): { target: string; html: string }[] {
  return EMBEDS.map(({ source, target }) => ({
    target,
    html: transformEmbed(fs.readFileSync(path.join(root, source), "utf8"), source),
  }));
}

function vendor(root: string) {
  const dir = path.join(root, VENDOR_DIR);
  fs.mkdirSync(dir, { recursive: true });
  for (const file of VENDOR_FILES) {
    fs.copyFileSync(
      path.join(root, "node_modules/three", file),
      path.join(dir, path.basename(file)),
    );
  }
}

function main() {
  const root = process.cwd();
  const args = process.argv.slice(2);
  if (args.includes("vendor")) {
    vendor(root);
    return;
  }
  const embeds = expectedEmbeds(root);
  if (args.includes("--check")) {
    const stale = embeds.filter(({ target, html }) => {
      const file = path.join(root, EMBED_DIR, target);
      return !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== html;
    });
    if (stale.length) {
      console.error(
        `embeds: stale ${stale.map((e) => e.target).join(", ")} (run scripts/embeds.ts)`,
      );
      process.exit(1);
    }
    console.log("embeds: up to date");
    return;
  }
  fs.mkdirSync(path.join(root, EMBED_DIR), { recursive: true });
  for (const { target, html } of embeds) fs.writeFileSync(path.join(root, EMBED_DIR, target), html);
  vendor(root);
  console.log(
    `embeds: wrote ${embeds.map((e) => e.target).join(", ")} and ${VENDOR_FILES.length} vendor files`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) main();
