#!/usr/bin/env bash
# Isolated card worktree (agents/PROTOCOL.md section 7): own branch, own ports, own Postgres databases,
# own Redis db index, dependencies installed. Parallel cards never share a dev server, a test server or data.
#
#   scripts/worktree.sh <n> [branch]   create (idempotent) and bootstrap .worktrees/<n>; default branch from board.ts get
#   scripts/worktree.sh --env <n>      print the card's env (ports, DB URLs), no side effects
#   scripts/worktree.sh --remove <n>   remove the worktree (refuses if dirty unless --force) and drop its databases
#
# In the worktree, agents load the env first:  set -a; . ./.env; set +a
# Slot = n mod 1000: web PORT 5000+slot (see.ts, `npm run dev`), PW_PORT 6000+slot (Playwright),
# RACE_SERVER_PORT 7000+slot, databases app_c<n> and app_c<n>_test, Redis db 1 + n mod 15.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(cd "$(dirname "$(git rev-parse --path-format=absolute --git-common-dir)")" && pwd)"

mode=create force=0
case "${1:-}" in
  --env) mode=env; shift ;;
  --remove) mode=remove; shift ;;
esac
[[ "${1:-}" == "--force" ]] && { force=1; shift; }
n="${1:-}"; n="${n#\#}"
[[ "$n" =~ ^[0-9]+$ ]] || { echo "usage: scripts/worktree.sh [--env|--remove [--force]] <n> [branch]"; exit 2; }
WT="$ROOT/.worktrees/$n"
slot=$(( n % 1000 ))
DB="app_c$n"

card_env() {
  cat <<EOF
# Generated by scripts/worktree.sh for card #$n. Local only; never commit.
DATABASE_URL="postgresql://app:app@localhost:5432/$DB?schema=public"
TEST_DATABASE_URL="postgresql://app:app@localhost:5432/${DB}_test?schema=public"
PORT="$(( 5000 + slot ))"
PW_PORT="$(( 6000 + slot ))"
SEE_BASE_URL="http://localhost:$(( 5000 + slot ))"
NEXT_PUBLIC_APP_URL="http://localhost:$(( 5000 + slot ))"
RACE_SERVER_PORT="$(( 7000 + slot ))"
NEXT_PUBLIC_RACE_SERVER_URL="http://localhost:$(( 7000 + slot ))"
RACE_SERVER_INTERNAL_URL="http://localhost:$(( 7000 + slot ))"
WEB_ORIGIN="http://localhost:$(( 5000 + slot ))"
REDIS_URL="redis://localhost:6379/$(( 1 + n % 15 ))"
RACE_TOKEN_SECRET="local-card-$n-$(printf '%s' "$ROOT" | shasum | cut -c1-24)"
DB_GUARD_ALLOWED_HOSTS=""
EOF
}

compose() { docker compose -f "$ROOT/docker-compose.yml" --project-directory "$ROOT" "$@"; }
psql_admin() { compose exec -T postgres psql -U app -d app -tAc "$1"; }
db_ready() { command -v docker >/dev/null && compose up -d --wait >/dev/null 2>&1; }

if [[ "$mode" == env ]]; then card_env; exit 0; fi

if [[ "$mode" == remove ]]; then
  if [[ -d "$WT" ]]; then
    if (( ! force )) && [[ -n "$(git -C "$WT" status --porcelain)" ]]; then
      echo "worktree: $WT has uncommitted changes; commit them or pass --force"; exit 1
    fi
    git -C "$ROOT" worktree remove --force "$WT"
    echo "worktree: removed $WT"
  fi
  if db_ready; then
    for d in "$DB" "${DB}_test"; do psql_admin "DROP DATABASE IF EXISTS \"$d\" WITH (FORCE)" >/dev/null; done
    echo "worktree: dropped $DB, ${DB}_test"
  fi
  exit 0
fi

branch="${2:-}"
if [[ -z "$branch" ]]; then
  branch="$(npx tsx scripts/board.ts get "$n" --comments 0 | sed -n 's/^branch: \([^ ]*\).*/\1/p')"
  [[ -n "$branch" ]] || { echo "worktree: could not resolve the branch for #$n"; exit 1; }
fi

if [[ ! -d "$WT" ]]; then
  git -C "$ROOT" fetch -q origin main
  if git -C "$ROOT" show-ref -q --verify "refs/heads/$branch"; then
    git -C "$ROOT" worktree add -q "$WT" "$branch"
  elif git -C "$ROOT" show-ref -q --verify "refs/remotes/origin/$branch"; then
    git -C "$ROOT" worktree add -q --track -b "$branch" "$WT" "origin/$branch"
  else
    git -C "$ROOT" worktree add -q -b "$branch" "$WT" origin/main
  fi
  echo "worktree: created $WT on $branch"
fi

card_env >"$WT/.env"
set -a; . "$WT/.env"; set +a

# Dependencies: an APFS clone of the main checkout's node_modules is near-instant; npm install then reconciles.
if [[ ! -d "$WT/node_modules" ]]; then
  if [[ -d "$ROOT/node_modules" && "$(uname)" == Darwin ]]; then cp -cR "$ROOT/node_modules" "$WT/node_modules"; fi
fi
(cd "$WT" && npm install --no-audit --no-fund --loglevel=error >/dev/null) || { echo "worktree: npm install failed in $WT"; exit 1; }
echo "worktree: deps ready"

# Databases on the shared local server (one stack for every worktree, always started from the main checkout).
if db_ready; then
  scripts/db-guard.sh "$DATABASE_URL"
  for d in "$DB" "${DB}_test"; do
    [[ "$(psql_admin "SELECT 1 FROM pg_database WHERE datname='$d'")" == 1 ]] || psql_admin "CREATE DATABASE \"$d\"" >/dev/null
  done
  if compgen -G "$WT/prisma/migrations/*/migration.sql" >/dev/null; then
    (cd "$WT" && npx prisma migrate deploy >/dev/null && DATABASE_URL="$TEST_DATABASE_URL" npx prisma migrate deploy >/dev/null)
  fi
  echo "worktree: databases $DB, ${DB}_test ready"
else
  echo "worktree: WARN docker unavailable; databases not prepared (cards that need a DB will fail their checks)"
fi
echo "worktree: ready $WT | web :$PORT | playwright :$PW_PORT | race :$RACE_SERVER_PORT | load env: set -a; . ./.env; set +a"
